### ISSUE TITLE
EclipseLink @Entity and MVC @RedirectScoped do not co-exist

### ISSUE THREAD

**Issue by sgparry** [eclipse-ee4j/krazo#152] opened 2020-02-05 00:59 UTC
If you try to persist an inject instance of a class tagged with @RedirectScoped using @Entity, the call to EntityManager.persist fails with:
javax.servlet.ServletException: java.lang.IllegalArgumentException: Object: com.example.mvcjpa.prg.Note[ id=0 ] is not a known Entity type.
This makes implementing Post Redirect Get with persistence difficult

**Comment by chkal** [comment] 2020-02-05 17:16
To be honest, I don't fully understand the reasoning behind mixing `@RedirectScoped` and `@Entity`. JPA entities are typically no CDI beans and that's why mixing those annotations doesn't work.

Could you perhaps share an example or describe what you are trying to achieve?

**Comment by Daniel-Dos** [comment] 2020-02-05 17:19
Hi,

I'm too not understanding the problem, but I have an example of use here ->

https://github.com/soujava/mvc-cxf-tomee/blob/master/src/main/java/org/superbiz/Messages.java


{  }

Em qua., 5 de fev. de 2020 às 14:16, Christian Kaltepoth <
notifications@github.com> escreveu:

**Comment by sgparry** [comment] 2020-02-06 06:48
What's wrong with persisting using CDI?

I merged this JPA [sample](https://github.com/payara/Payara-Examples/tree/master/javaee/simple-jpa-example) described in this [tutorial](https://blog.payara.fish/how-to-store-and-retrieve-data-from-a-database) with Ivar Grimstad's mvc post redirect get sample from [here](https://github.com/ivargrimstad/mvc-samples/tree/master/post-redirect-get), updated to Krazo.

The `ReservationService` class in IG's code implements the model facade, but only stores the `Reservation` objects in memory. The Payara code includes a `PersonRepository` class that acts as the model facade for `Person` entities and is able to persist the model to a database using the @Entity annotation and an injected entity manager. It has a simple controller for handling POSTs and GETs, but lacks a redirect or a view. I simply used the model code from Payara (with some code form Netbeans' templates) with IG's controller and view.

The code copies the incoming form bean fields into the persistable entity, persists that using the service object, then forwards the entity to a second controller via a redirect. 

Here is a partial example:

Note.java:
```
package com.example.mvcjpa.prg;

import java.io.Serializable;
import javax.inject.Named;
import javax.mvc.RedirectScoped;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
@RedirectScoped
@Named
public class Note implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    
    private String text;

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }
    
    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Note)) {
            return false;
        }
        Note other = (Note) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "com.example.mvcjpa.prg.Note[ id=" + id + " ]";
    }
    
}
```
NoteService.java

```
package com.example.mvcjpa.service;

import com.example.mvcjpa.prg.Note;
import com.example.mvcjpa.service.exceptions.NonexistentEntityException;
import java.io.Serializable;
import java.util.List;
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Named;
import javax.persistence.EntityManager;
import javax.persistence.Query;
import javax.persistence.EntityNotFoundException;
import javax.persistence.PersistenceContext;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Root;
import javax.transaction.Transactional;
import static javax.transaction.Transactional.TxType.REQUIRED;

@Named
@ApplicationScoped
public class NoteService implements Serializable {

    @PersistenceContext(unitName = "SAMPLE_PU")
    private EntityManager em;

    @Transactional(REQUIRED)
    public void create(Note note) {
        try {
            em.persist(note);
        } finally {
        }
    }

    @Transactional(REQUIRED)
    public void edit(Note note) throws NonexistentEntityException, Exception {
        try {
            note = em.merge(note);
        } catch (Exception ex) {
            String msg = ex.getLocalizedMessage();
            if (msg == null || msg.length() == 0) {
                Long id = note.getId();
                if (findNote(id) == null) {
                    throw new NonexistentEntityException("The note with id " + id + " no longer exists.");
                }
            }
            throw ex;
        } finally {
        }
    }

    @Transactional(REQUIRED)
    public void destroy(Long id) throws NonexistentEntityException {
        try {
            Note note;
            try {
                note = em.getReference(Note.class, id);
                note.getId();
            } catch (EntityNotFoundException enfe) {
                throw new NonexistentEntityException("The note with id " + id + " no longer exists.", enfe);
            }
            em.remove(note);
        } finally {
        }
    }

    @Transactional(REQUIRED)
    public List<Note> findNoteEntities() {
        return findNoteEntities(true, -1, -1);
    }

    @Transactional(REQUIRED)
    public List<Note> findNoteEntities(int maxResults, int firstResult) {
        return findNoteEntities(false, maxResults, firstResult);
    }

    @Transactional(REQUIRED)
    private List<Note> findNoteEntities(boolean all, int maxResults, int firstResult) {
        try {
            CriteriaQuery cq = em.getCriteriaBuilder().createQuery();
            cq.select(cq.from(Note.class));
            Query q = em.createQuery(cq);
            if (!all) {
                q.setMaxResults(maxResults);
                q.setFirstResult(firstResult);
            }
            return q.getResultList();
        } finally {
        }
    }

    @Transactional(REQUIRED)
    public Note findNote(Long id) {
        try {
            return em.find(Note.class, id);
        } finally {
        }
    }

    @Transactional(REQUIRED)
    public int getNoteCount() {
        try {
            CriteriaQuery cq = em.getCriteriaBuilder().createQuery();
            Root<Note> rt = cq.from(Note.class);
            cq.select(em.getCriteriaBuilder().count(rt));
            Query q = em.createQuery(cq);
            return ((Long) q.getSingleResult()).intValue();
        } finally {
        }
    }
    
}

```

NoteController.java
```
package com.example.mvcjpa.prg;

import com.example.mvcjpa.service.NoteService;
import static java.util.stream.Collectors.toList;
import javax.inject.Inject;
import javax.mvc.Controller;
import javax.mvc.View;
import javax.mvc.binding.BindingResult;
import javax.mvc.security.CsrfProtected;
import javax.validation.Valid;
import javax.ws.rs.BeanParam;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.core.Response;
import static javax.ws.rs.core.Response.Status.BAD_REQUEST;

@Controller
@Path("notes")
public class NoteController {
    @Inject
    private Note note;
    @Inject
    private NoteService noteService;
    
    @Inject
    private BindingResult br;

    @Inject
    private Messages messages;

    @GET
    @View("note.jsp")
    @Path("new")
    public void emptyNote() {
    }
    
    @CsrfProtected
    @POST
    @Path("new")
    public Response createNote(@Valid @BeanParam NoteFormBean form) {
        
        note.setId(form.getId());
        note.setText(form.getText());

        if (br.isFailed()) {
            messages.setErrors(
                    br.getAllErrors().stream()
                            .collect(toList()));
            
            return Response.status(BAD_REQUEST).entity("note.jsp").build();
        }

        noteService.create(note); // blows up here

        return Response.ok("redirect:savednote").build();
    }
}
```
I have created a workaround that uses separate instances, a local one for the persist and the injected one for the redirect and a copy method, but that should not be really necessary

**Comment by erdlet** [comment] 2020-02-11 07:52
I'm not sure if this is really a MVC specific problem, as the bean itself seems to be instantiated but JPA doesn't recognize it as `Entity`. I can remember this happened in Eclipse Link because of some missing setting in persistence.xml. Anyway, would be great if you can push the whole example project to Github, so we can check this.

Nevertheless, I don't think PRG should rely on `RedirectScoped` beans, because you leave your transactional context when redirecting and probably rely on invalid data on the next view. The most common solution for PRG I know (and which is used by most MVC frameworks, e.g. Rails) is to redirect to a sub-resource, like `/notes/{id}` in your case, and reload the bean from the database. This way you get always the latest data and you don't get into trouble with JPA because you work on a detached bean.

**Comment by chkal** [comment] 2020-02-15 08:24
> What's wrong with persisting using CDI?

Well, a JPA entity is managed by JPA and therefore using CDI scope annotations doesn't make sense. What would be the expected behavior of injecting an instance of a JPA entity into some class or referencing it via an EL expression. How should CDI know which entity to load in this case?

**Comment by chkal** [comment] 2020-02-15 08:26
BTW: I created a minimal TODO app using MVC some time ago which demonstrates some general patterns including PRG. I didn't update the example for quite some time, but it may be worth a look:

https://github.com/chkal/todo-mvc

**Comment by erdlet** [comment] 2020-03-17 12:13
As there is no feedback or any other reaction since more than a month, I'll close this issue for now. If there are any questions left, please feel free to re-open it.

**Closed by erdlet** 2020-03-17 12:13 UTC
Labels: question
