### ISSUE TITLE
Tomee 9.0.0 M7 Plus

### ISSUE THREAD

**Issue by ignramgar** [eclipse-ee4j/krazo#290] opened 2021-12-28 11:49 UTC
POM configuration:

```xml
<dependency>
  <groupId>jakarta.mvc</groupId>
  <artifactId>jakarta.mvc-api</artifactId>
  <version>2.0.0</version>
</dependency>
		
<dependency>
  <groupId>org.eclipse.krazo</groupId>
  <artifactId>krazo-core</artifactId>
  <version>2.0.0</version>
</dependency>
		
<dependency>
  <groupId>org.eclipse.krazo</groupId>
  <artifactId>krazo-cxf</artifactId>
  <version>2.0.0</version>
</dependency>
```

Error when starting the server:

```
INFO: Configuring enterprise application: XXXXXX\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps\pocJEEMVCTomee8
[severity=FATAL_ERROR,message=unexpected element (uri:"https://jakarta.ee/xml/ns/jakartaee", local:"web-fragment"). Expected elements are <{http://java.sun.com/xml/ns/javaee}handler-chains>,<{http://java.sun.com/xml/ns/javaee}web-fragment>,locator=[node=null,object=null,url=null,line=24,col=29,offset=-1]]
Dec 28, 2021 12:41:02 PM org.apache.openejb.config.ReadDescriptors mergeWebFragments
WARNING: can't read UrlSource{url=jar:file:XXXXXXX/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pocJEEMVCTomee8/WEB-INF/lib/krazo-core-2.0.0.jar!/META-INF/web-fragment.xml}
jakarta.xml.bind.UnmarshalException: unexpected element (uri:"https://jakarta.ee/xml/ns/jakartaee", local:"web-fragment"). Expected elements are <{http://java.sun.com/xml/ns/javaee}handler-chains>,<{http://java.sun.com/xml/ns/javaee}web-fragment>
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.handleEvent(UnmarshallingContext.java:714)
	at com.sun.xml.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:232)
	at com.sun.xml.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:227)
	at com.sun.xml.bind.v2.runtime.unmarshaller.Loader.reportUnexpectedChildElement(Loader.java:94)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext$DefaultRootLoader.childElement(UnmarshallingContext.java:1119)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:544)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:526)
	at com.sun.xml.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:138)
	at java.xml/org.xml.sax.helpers.XMLFilterImpl.startElement(XMLFilterImpl.java:551)
	at org.apache.openejb.jee.JaxbJavaee$NoSourceFilter.startElement(JaxbJavaee.java:360)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:510)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:613)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3060)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:836)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
	at java.xml/org.xml.sax.helpers.XMLFilterImpl.parse(XMLFilterImpl.java:357)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:228)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:199)
	at jakarta.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:123)
	at jakarta.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:106)
```

Executed from Eclipse:
Version: 2021-12 (4.22.0)
Build id: 20211202-1639

With facets:
![image](https://user-images.githubusercontent.com/4292335/147563208-233aea0d-9434-4bc7-b41e-4702de6e3ea9.png)

**Comment by erdlet** [comment] 2021-12-28 14:47
Hi, thanks for the report.

It seems that this Milestone of TomEE hasn't migrated their `web.xml` schema properly, as it expects the legacy Java EE namespace:

```
Expected elements are <{http://java.sun.com/xml/ns/javaee}handler-chains>,<{http://java.sun.com/xml/ns/javaee}web-fragment>
```

As this release of TomEE is just a milestone release, it may be an idea to report this exception to the TomEE team.

Also please note, that Krazo CXF will be dropped with version 3.0.0 as it is too painful to maintain it.

**Comment by dmaidaniuk** [comment] 2022-01-12 04:33
@ignramgar, Could you please share some reproducing project for your issue? I can take a look how to solve/workaround it.

**Comment by erdlet** [comment] 2022-05-27 20:33
As there is no more feedback since 4 months I'll close this issue. Please reopen if further questions occur. Thanks.

**Closed by erdlet** 2022-05-27 20:33 UTC
