### ISSUE TITLE
Exception sending context destroyed event to listener instance of class [org.eclipse.krazo.servlet.KrazoServletContextListener]

### ISSUE THREAD

**Issue by Victz** [eclipse-ee4j/krazo#164] opened 2020-03-01 10:20 UTC
Hi 

sorry I am not sure if this is an issue. I am trying to setup Krazo with resteasy at tomcat, web can launch successfully but there is error in tomcat log. appreciate if anyone can help. 

no such error in jboss 7.2 and wildly.

```
01-Mar-2020 17:58:30.578 SEVERE [ContainerBackgroundProcessor[StandardEngine[Catalina]]] org.apache.catalina.core.StandardContext.listenerStop Exception sending context destroyed event to listener instance of class [org.eclipse.krazo.servlet.KrazoServletContextListener]
	java.lang.AbstractMethodError
		at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:4746)
		at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5403)
		at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
		at org.apache.catalina.core.StandardContext.reload(StandardContext.java:3752)
		at org.apache.catalina.startup.HostConfig.reload(HostConfig.java:1395)
		at org.apache.catalina.startup.HostConfig.checkResources(HostConfig.java:1368)
		at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1603)
		at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:304)
		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
		at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1159)
		at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1381)
		at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1385)
		at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1353)
		at java.lang.Thread.run(Thread.java:748)
```

environment: 
tomcat 8.5.50
jdk1.8.0_241
netbeans 11.1

pom.xml 

```xml
   <properties>
        <endorsed.dir>${project.build.directory}/endorsed</endorsed.dir>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <jakartaee.version>8.0.0</jakartaee.version>
        <microprofile.version>3.2</microprofile.version>
        <resteasy.version>3.6.1.Final</resteasy.version>
    </properties>

    <dependencies>
        <dependency> 
            <groupId>jakarta.platform</groupId> 
            <artifactId>jakarta.jakartaee-web-api</artifactId> 
            <version>${jakartaee.version}</version> 
        </dependency> 
        <!--        <dependency>
            <groupId>javax</groupId>
            <artifactId>javaee-web-api</artifactId>
            <version>8.0</version>
        </dependency>-->
        <dependency>
            <groupId>org.eclipse.microprofile</groupId>
            <artifactId>microprofile</artifactId>
            <version>${microprofile.version}</version>
            <type>pom</type>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>jstl</artifactId>
            <version>1.2</version>
        </dependency>
        <!-- Weld -->
        <dependency>
            <groupId>org.jboss.weld.servlet</groupId>
            <artifactId>weld-servlet-core</artifactId>
            <version>3.0.5.Final</version>
        </dependency>

        <!-- RESTEasy -->
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-cdi</artifactId>
            <version>${resteasy.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-servlet-initializer</artifactId>
            <version>${resteasy.version}</version>
        </dependency>

        <!-- Bean Validation -->
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-validator-provider-11</artifactId>
            <version>${resteasy.version}</version>
        </dependency>

        <!-- MVC + Eclipse Krazo for RESTEasy -->
        <dependency>
            <groupId>javax.mvc</groupId>
            <artifactId>javax.mvc-api</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.krazo</groupId>
            <artifactId>krazo-resteasy</artifactId>
            <version>1.1.0-M1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.9</version>
        </dependency>
        <!-- MySQL connector -->
        <!-- <dependency> <groupId>mysql</groupId> <artifactId>mysql-connector-java</artifactId> 
        <version>8.0.18</version> </dependency> -->
        <dependency>
            <groupId>org.apache.derby</groupId>
            <artifactId>derby</artifactId>
            <version>10.14.2.0</version>
        </dependency>
        <!-- Hibernate 5.3.7 Final -->
        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-core</artifactId>
            <version>5.3.7.Final</version>
        </dependency>
```

web.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>

<web-app xmlns="http://xmlns.jcp.org/xml/ns/javaee"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_3_1.xsd"
         version="3.1">

    <listener>
        <listener-class>org.jboss.weld.environment.servlet.Listener</listener-class>
    </listener>    
    <resource-env-ref>
        <resource-env-ref-name>BeanManager</resource-env-ref-name>
        <resource-env-ref-type>javax.enterprise.inject.spi.BeanManager</resource-env-ref-type>
    </resource-env-ref>
    
    <context-param>
        <param-name>resteasy.preferJacksonOverJsonB</param-name>
        <param-value>false</param-value>
    </context-param>    
    <!--http://docs.jboss.org/resteasy/docs/3.6.1.Final/userguide/html_single/index.html#d4e143 -->
    <context-param>
        <param-name>resteasy.injector.factory</param-name>
        <param-value>org.jboss.resteasy.cdi.CdiInjectorFactory</param-value>
    </context-param>
    
    <filter>
        <filter-name>Resteasy</filter-name>
        <filter-class>org.jboss.resteasy.plugins.server.servlet.FilterDispatcher</filter-class>
        <init-param>
            <param-name>javax.ws.rs.Application</param-name>
            <param-value>com.victz.test.utils.RestApplication</param-value>
        </init-param>
    </filter>
    <filter-mapping>
        <filter-name>Resteasy</filter-name>
        <url-pattern>/*</url-pattern>
    </filter-mapping>  
    
    <session-config>
        <session-timeout>30</session-timeout>
    </session-config>
    
    <welcome-file-list>
        <welcome-file>/</welcome-file>
    </welcome-file-list>
    
    <error-page>
        <error-code>401</error-code>
        <location>/alert/401.html</location>
    </error-page>
    <error-page>
        <error-code>403</error-code>
        <location>/alert/403.html</location>
    </error-page>
    <error-page>
        <error-code>404</error-code>
        <location>/alert/404.html</location>
    </error-page>
    <error-page>
        <error-code>500</error-code>
        <location>/alert/500.html</location>
    </error-page>
</web-app>
```

```java
package com.victz.test.utils;

import java.util.Set;
import javax.ws.rs.core.Application;

/**
 *
 * @author shawn
 */
//@ApplicationPath("/")
public class RestApplication extends Application {

    @Override
    public Set<Class<?>> getClasses() {
        Set<Class<?>> resources = new java.util.HashSet<>();
        addRestResourceClasses(resources);
        return resources;
    }

    /**
     * Do not modify addRestResourceClasses() method. It is automatically populated with all resources defined in the project. If required, comment out calling this method in getClasses().
     */
    private void addRestResourceClasses(Set<Class<?>> resources) { 
        resources.add(com.victz.test.controller.IndexController.class);
        resources.add(com.victz.test.utils.ApplicationConfig.class);
        resources.add(com.victz.test.utils.RequestConfig.class);
        resources.add(com.victz.test.utils.SessionConfig.class);

    }

}
```

```java
package com.victz.test.controller;


import com.victz.test.utils.ApplicationConfig;
import com.victz.test.utils.RequestConfig;
import com.victz.test.utils.SessionConfig;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.mvc.Controller;
import javax.mvc.MvcContext;
import javax.mvc.View;
import javax.ws.rs.GET;
import javax.ws.rs.Path;

/**
 *
 * @author shawn
 */
@Path("")
@RequestScoped
public class IndexController {

//    @Context
//    HttpServletRequest request;
    @Inject
    MvcContext mvcContext;
    @Inject
    RequestConfig requestConfig;
    @Inject
    SessionConfig sessionConfig;
    @Inject
    ApplicationConfig applicationConfig;

    @Controller
    @GET
    @Path("")
    @View("index.jsp")
    public void welcome() {
    }

    @Controller
    @GET
    @Path("index")
    @View("index.jsp")
    public void index() {
    }
}
```

**Comment by chkal** [comment] 2020-03-01 15:54
From the API docs of `AbstractMethodError`:

> Thrown when an application tries to call an abstract method.

And from the stacktrace it looks like this is thrown when Tomcat tries to invoke `KrazoServletContextListener.contextDestroyed()`. However, this method is actually not implemented in our listener. 

https://github.com/eclipse-ee4j/krazo/blob/6759cd29bd1a395258b6c105d35e444c57571b8d/core/src/main/java/org/eclipse/krazo/servlet/KrazoServletContextListener.java

But this should actually work (and works on other containers), because `contextDestroyed` is defined with a default implementation in `ServletContextListener`.

So my guess is that you either are not running the container with JDK8 or that there is some older version of the Servlet API on your classpath. Could you post the effective contents of `WEB-INF/lib`?

**Comment by Victz** [comment] 2020-03-01 16:08
thank you for your prompt reply. please see below list of files under WEB-INF/lib 

activation-1.1.1.jar
antlr-2.7.7.jar
apache-mime4j-0.6.jar
byte-buddy-1.8.17.jar
cdi-api-2.0.jar
classmate-1.3.4.jar
commons-codec-1.10.jar
commons-io-2.5.jar
commons-lang3-3.9.jar
commons-logging-1.1.1.jar
derby-10.14.2.0.jar
derbyclient-10.14.2.0.jar
dom4j-2.1.1.jar
hibernate-commons-annotations-5.0.4.Final.jar
hibernate-core-5.3.7.Final.jar
hibernate-entitymanager-5.3.7.Final.jar
hibernate-jpa-2.0-api-1.0.1.Final.jar
hibernate-validator-5.2.4.Final.jar
httpclient-4.5.4.jar
httpcore-4.4.7.jar
jakarta.jakartaee-web-api-8.0.0.jar
jandex-2.0.5.Final.jar
javassist-3.23.1-GA.jar
javax.activation-api-1.2.0.jar
javax.el-api-3.0.0.jar
javax.inject-1.jar
javax.interceptor-api-1.2.jar
javax.json.bind-api-1.0.jar
javax.mail-1.5.6.jar
javax.mvc-api-1.0.0.jar
javax.persistence-api-2.2.jar
jaxb-core-2.3.0.jar
jaxb-impl-2.3.0.jar
jboss-annotations-api_1.2_spec-1.0.0.Final.jar
jboss-annotations-api_1.3_spec-1.0.0.Final.jar
jboss-classfilewriter-1.2.3.Final.jar
jboss-el-api_3.0_spec-1.0.7.Final.jar
jboss-interceptors-api_1.2_spec-1.0.0.Final.jar
jboss-jaxb-api_2.3_spec-1.0.0.Final.jar
jboss-jaxrs-api_2.1_spec-1.0.1.Final.jar
jboss-logging-3.2.1.Final.jar
jboss-transaction-api_1.2_spec-1.1.1.Final.jar
jcip-annotations-1.0.jar
jstl-1.2.jar
krazo-core-1.0.0.jar
krazo-resteasy-1.0.0.jar
reactive-streams-1.0.2.jar
resteasy-cdi-3.6.1.Final.jar
resteasy-client-3.6.1.Final.jar
resteasy-jaxb-provider-3.6.1.Final.jar
resteasy-jaxrs-3.6.1.Final.jar
resteasy-multipart-provider-3.6.1.Final.jar
resteasy-servlet-initializer-3.6.1.Final.jar
resteasy-validator-provider-11-3.6.1.Final.jar
validation-api-1.1.0.Final.jar
weld-api-3.0.SP4.jar
weld-core-impl-3.0.5.Final.jar
weld-environment-common-3.0.5.Final.jar
weld-jsf-3.0.5.Final.jar
weld-probe-core-3.0.5.Final.jar
weld-servlet-core-3.0.5.Final.jar
weld-spi-3.0.SP4.jar
weld-web-3.0.5.Final.jar

**Comment by chkal** [comment] 2020-03-01 16:23
Including `jakarta.jakartaee-web-api-8.0.0.jar` in your project is a bit dangerous, because it includes APIs already provided by Tomcat (like the Servlet API) and other APIs which you actually need (like CDI). I would recommend removing this dependency and replace it with dependencies for individual specs or at least change it to `provided` scope.

**Comment by Victz** [comment] 2020-03-01 16:37
thank you very much for the advice. yes it was provided scope when I ran on jboss and wildly. I removed scope after I switched to tomcat during debugging. :)

**Comment by chkal** [comment] 2020-03-01 16:42
So this fixed the problem? If so, feel free to close the issue. Thanks.

**Comment by Victz** [comment] 2020-03-01 16:54
sorry Christian, the error log still exist. but seems it's just a warning. the web looks working fine.

**Comment by chkal** [comment] 2020-03-02 16:31
Could you share a sample application to reproduce this issue?

**Comment by erdlet** [comment] 2020-07-06 07:15
As there is no feedback since more than 3 months, I'll close this for now. If there are futher questions or new information we can reopen this issue :)

**Closed by erdlet** 2020-07-06 07:15 UTC
Labels: question
