### ISSUE TITLE
SRVE8115W and SRVE8094W warnings at every request in OpenLiberty

### ISSUE THREAD

**Issue by mthmulders** [eclipse-ee4j/krazo#132] opened 2020-01-03 15:05 UTC
Not sure if this indicates a real problem, but thought I'd report it anyway.

When I deploy my [sample MVC application](https://github.com/mthmulders/openliberty-mvc) to OpenLiberty and I access it through my web browser, the OpenLiberty logs shows this

    [INFO] [WARNING ] SRVE8115W: WARNING: Cannot set status. Response already committed.
    [INFO] [WARNING ] SRVE8094W: WARNING: Cannot set header. Response already committed.  Stack trace of errant attempt to set header: 
    [INFO]         at com.ibm.ws.webcontainer.srt.SRTServletResponse.setHeader(SRTServletResponse.java:1759)
    [INFO]         at [internal classes].(Unknown Source)
    [INFO]         at org.eclipse.krazo.core.ViewableWriter$DelegatingServletOutputStream.write(ViewableWriter.java:248)
    [INFO]         at java.base/java.io.OutputStream.write(OutputStream.java:157)
    [INFO]         at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)
    [INFO]         at java.base/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:312)
    [INFO]         at java.base/sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:316)
    [INFO]         at java.base/sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:153)
    [INFO]         at java.base/java.io.OutputStreamWriter.flush(OutputStreamWriter.java:254)
    [INFO]         at java.base/java.io.PrintWriter.flush(PrintWriter.java:396)
    [INFO]         at org.eclipse.krazo.core.ViewableWriter.writeTo(ViewableWriter.java:169)
    [INFO]         at org.eclipse.krazo.core.ViewableWriter.writeTo(ViewableWriter.java:70)
    [INFO]         at org.apache.cxf.jaxrs.utils.JAXRSUtils$3.run(JAXRSUtils.java:1479)
    [INFO]         at [internal classes].(Unknown Source)

From what I've seen debugging, the following happens:

1. [`HttpServletResponse#setHeader()`](https://javaee.github.io/javaee-spec/javadocs/javax/servlet/http/HttpServletResponse.html#setHeader-java.lang.String-java.lang.String-) is invoked, probably by OpenLiberty itself. It sets the `X-Powered-By` header with value `Servlet/4.0`.
When I manually add calls to setHeader inside my Krazo Controller, they also happen at this stage.
1. [`ServletResponse#flushBuffer()`](https://javaee.github.io/javaee-spec/javadocs/javax/servlet/ServletResponse.html#flushBuffer--) is invoked by [`RequestDispatcher#forward`](https://javaee.github.io/javaee-spec/javadocs/javax/servlet/RequestDispatcher.html#forward-javax.servlet.ServletRequest-javax.servlet.ServletResponse-), which is in turn invoked by `org.eclipse.krazo.engine.ServletViewEngine#forwardRequest`.
1. [`HttpServletResponse#setHeader()`](https://javaee.github.io/javaee-spec/javadocs/javax/servlet/http/HttpServletResponse.html#setHeader-java.lang.String-java.lang.String-) is invoked. It sets the `Date` header with value `Fri, 03 Jan 2020 14:43:37 GMT`. It is invoked by `org.eclipse.krazo.core.ViewableWriter#writeTo`

As I said, I'm not sure this is an indication of something severely going wrong. The application seems to behave fine, other than these warnings being logged. It is annoying however since the message is logged *for every request*, so this really pollutes the log files.

As a wise person once said:

> A warning is an error in the making

Of course, if there's anything I can do (e.g. provide full stacktraces, or whatever), please let me know!

**Comment by chkal** [comment] 2020-01-04 10:39
Hi @mthmulders. Thanks a lot for bringing this up. I also saw these exceptions while working on the Liberty/CXF support but didn't find time yet to investigate. Your analysis is very helpful.

To be honest, the thing that confuses me is that `RequestDispatcher#forward` flushes the response. This doesn't look correct to me. And I don't see a good reason why the buffer is flushed at this point. Actually, the API docs of `RequestDispatcher#forward` even state:

> Uncommitted output in the response buffer is automatically cleared before the forward.

So isn't flushing the buffers as part of the forward even a violation of the spec in this case?

@eclipse-ee4j/ee4j-krazo-committers Other thoughts?

**Comment by erdlet** [comment] 2020-01-07 07:55
> So isn't flushing the buffers as part of the forward even a violation of the spec in this case?

:+1: in case this also occurs when a forward without Krazo is performed with the same warnings. Would be great if someone can check this. I don't know if I'll find some time to have a look on this today.

**Comment by chkal** [comment] 2020-01-07 11:37
I agree that it would be interesting to know if this is reproducible in a plain Servlet app which sets a header and forwards the request after that. I also won't find time for this today, but maybe tomorrow.

**Comment by mthmulders** [comment] 2020-01-09 13:18
I've created [openliberty-requestforward](https://github.com/mthmulders/openliberty-requestforward). It's a web app with just a Servlet and a JSP, and the Servlet uses the RequestDispatcher#forward method to dispatch the request to the JSP. This example does not log the SRVE8115W and SRVE8094W warnings.

**Comment by chkal** [comment] 2020-01-09 20:16
@mthmulders Thanks a lot for sharing the testapp.

I guess you app needs a call to `response.setHeader()` before forwarding the request to reproduce the issue. Or am I missing something? At least this was my understanding of the underlying issue.

**Comment by mthmulders** [comment] 2020-01-10 07:00
@chkal My MVC app doesn't have any user code that sets a header. So the OpenLiberty testapp doesn't have it, either.
So a "plain" servlet-plus-jsp app does _not_ log the SRVE8115W and SRVE8094W warnings, but adding Krazo/MVC to the mix _does_ log them.
Both are running on the exact same version of OpenLiberty, 19.0.0.12.

**Comment by erdlet** [comment] 2020-01-10 09:26
@mthmulders thanks for testing this issue without Krazo.

> My MVC app doesn't have any user code that sets a header

I debugged this issue for some time now and found at least where this headers and status are being  set:
- [response.setStatus](https://github.com/OpenLiberty/open-liberty/blob/fb2add68ea341709c5bfda7c64962eb18dbe4be5/dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/src/org/apache/cxf/transport/http/AbstractHTTPDestination.java#L662)
- [copy to headers](https://github.com/OpenLiberty/open-liberty/blob/fb2add68ea341709c5bfda7c64962eb18dbe4be5/dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/src/org/apache/cxf/transport/http/AbstractHTTPDestination.java#L667)

This code is triggered when the output stream is going to be flushed.
These warnings also occur when I comment out the explicit `responseWriter#flush`:
```
[INFO] [WARNING ] SRVE8115W: WARNING: Cannot set status. Response already committed.
[INFO] [WARNING ] SRVE8094W: WARNING: Cannot set header. Response already committed.  Stack trace of errant attempt to set header: 
[INFO]         at com.ibm.ws.webcontainer.srt.SRTServletResponse.setHeader(SRTServletResponse.java:1759)
[INFO]         at [internal classes].(Unknown Source)
```
I guess this happens when the Liberty implementation flushes the output stream by itself.

After this I tried to find the place where the response gets flushed, but unfortunately I didn't find anything. @mthmulders maybe you have a callstack from your debugging where I can see the stack? Would be really great :)

Anyways, could be the "context switch" between Servlet / JSP API and JAX-RS be a problem? I think about something like the Servlet / JSP API finishes to process the response and afterwards JAX-RS wants to write into the committed response and isn't aware of the response's status.

**Comment by chkal** [comment] 2020-01-10 10:44
@mthmulders:

> My MVC app doesn't have any user code that sets a header. So the OpenLiberty testapp doesn't have it, either.

My idea was to reproduce this issue without Krazo and according to your original description there seems to be some `setHeader()` call before the response is forwarded which *may* cause these warnings.

@erdlet 

> I debugged this issue for some time now and found at least where this headers and status are being set
> I guess this happens when the Liberty implementation flushes the output stream by itself.

Thanks for debugging. I guess it is fine that both methods are called as part of the flushing. The real issue seems to be that at this point the response is already committed. According to the initial information provided by @mthmulders the commit happens as part of the forward in `RequestDispatcher#forward`. And actually the `forward` method should NEVER commit the response.

> Anyways, could be the "context switch" between Servlet / JSP API and JAX-RS be a problem? I think about something like the Servlet / JSP API finishes to process the response and afterwards JAX-RS wants to write into the committed response and isn't aware of the response's status.

That's definitely possible and most likely the reason for this warning.

I'll also try to find some time to dig into this, but I'm quite busy with pushing out the final versions as part of the MVC 1.0 release.

**Comment by mthmulders** [comment] 2020-01-10 12:44
> My idea was to reproduce this issue without Krazo and according to your original description there seems to be some `setHeader()` call before the response is forwarded which _may_ cause these warnings.

I understand the way of thinking and had more or less the expectation that the warning would also be logged when using only Servlet and JSP technology. Turns out the expectation is not confirmed...

> After this I tried to find the place where the response gets flushed, but unfortunately I didn't find anything. @mthmulders maybe you have a callstack from your debugging where I can see the stack? Would be really great :)

See https://gist.github.com/mthmulders/1bd5659d7ffc79e6084073d901d76451

**Comment by chkal** [comment] 2020-01-10 16:20
@mthmulders Thanks a lot!

So it looks like the response is committed because Liberty calls this method as part of the `dispatch`:

https://github.com/OpenLiberty/open-liberty/blob/gm-19.0.0.12/dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebAppRequestDispatcher.java#L1537

This method (`dispatch`) is over 500 lines long. :scream:  I guess it won't be easy for us to find the root cause in there. :disappointed:

**Comment by mthmulders** [comment] 2020-01-10 20:53
I've put a breakpoint in SRTServletResponse#commit to see when it gets invoked. It's _not_ from [WebAppRequestDispatcher.java#L1537](https://github.com/OpenLiberty/open-liberty/blob/gm-19.0.0.12/dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebAppRequestDispatcher.java#L1537), but it's from [WebAppRequestDispatcher.java#L1410](https://github.com/OpenLiberty/open-liberty/blob/gm-19.0.0.12/dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebAppRequestDispatcher.java#L1410). Still inside that enormous `dispatch()` method, though. The stack trace is in [this gist](#)

My feeling is that line 1410 causes the JSP to render (and thus write output), but I'm not too sure.

**Comment by chkal** [comment] 2020-01-11 08:22
@mthmulders Thanks a lot. Maybe I'll find some time today to have a deeper look.

**Comment by chkal** [comment] 2020-01-16 06:10
A small update. Unfortunately I didn't find any time yet to have a deeper look. But I hope I'll find some in the next days.

**Comment by jefrog1844** [comment] 2020-01-30 04:27
Just started a basic program with krazo RC1 today and have the same issue.  I'm using OpenLiberty.


These are the warnings:
[WARNING ] SRVE8115W: WARNING: Cannot set status. Response already committed.
[WARNING ] SRVE8094W: WARNING: Cannot set header. Response already committed.  Stack trace of errant attempt to set header: 
        at com.ibm.ws.webcontainer.srt.SRTServletResponse.setHeader(SRTServletResponse.java:1759)
        at [internal classes].(Unknown Source)
        at org.eclipse.krazo.core.ViewableWriter$DelegatingServletOutputStream.write(ViewableWriter.java:248)
        at java.io.OutputStream.write(OutputStream.java:116)
        at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
        at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at java.io.PrintWriter.flush(PrintWriter.java:320)
        at org.eclipse.krazo.core.ViewableWriter.writeTo(ViewableWriter.java:169)
        at org.eclipse.krazo.core.ViewableWriter.writeTo(ViewableWriter.java:70)
        at org.apache.cxf.jaxrs.utils.JAXRSUtils$3.run(JAXRSUtils.java:1479)
        at [internal classes].(Unknown Source)

These are my dependencies:
   <dependencies>
        <dependency>
            <groupId>jakarta.platform</groupId>
            <artifactId>jakarta.jakartaee-api</artifactId>
            <version>8.0.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.eclipse.krazo</groupId>
            <artifactId>krazo-parent</artifactId>
            <version>1.0.0-RC1</version>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>org.eclipse.krazo</groupId>
            <artifactId>krazo-cxf</artifactId>
            <version>1.0.0-RC1</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.krazo</groupId>
            <artifactId>krazo-core</artifactId>
            <version>1.0.0-RC1</version>
        </dependency>
    </dependencies>

This is my controller

package com.podfx.dfmea;

import javax.inject.Inject;
import javax.mvc.Controller;
import javax.mvc.Models;
import javax.mvc.View;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.Response;

@Controller
@Path("hello")
public class HelloController {
    
   @Inject
   private Models models;
   
   @Inject
   private DfmeaFacade facade;
   
   @Context
   private HttpServletRequest request;
    
    @GET
    @Path("void")
    @View("helloVoid.jsp")
    public void helloVoid() {
        models.put("context", getContext());
        models.put("dfmea", facade.getDfmeaDetail(1L));
    }
    
    @GET
    @Path("string")
    public String goodbyeString() {
        models.put("context", getContext());
        return "helloString.jsp";
    }
    
    @GET
    @Path("response")
    public Response helloResponse(){
        models.put("context", getContext());
        return Response.status(Response.Status.OK).entity("helloResponse.jsp").build();
    }
    
    @GET
    @Path("bye")
    @View("goodbye.jsp")
    public void goodbye() {
       HttpSession s = request.getSession(false);
       if(s != null) {
           s.invalidate();
       }
    }
    
    private UserContext getContext() {
        HttpSession s = request.getSession(true);
        UserContext context = (UserContext) s.getAttribute("context");
        if(context == null) {
            context = new UserContext();
            s.setAttribute("context", context);
        }
        context.setSessionId(s.getId());
        return context;
    }
}

**Comment by chkal** [comment] 2020-01-30 05:43
Thanks for sharing these details.

Unfortunately, as mentioned above, Krazo doesn't work very well with CXF (and therefore with OpenLiberty and TomEE) at the moment. As Krazo is basically a JAX-RS extension, we are using many (all?) JAX-RS SPIs. While working on Krazo we discovered and reported JAX-RS specification incompatibilities in all JAX-RS implementations and even obscurities in the JAX-RS spec itself. So my current guess is that the known problems with CXF are caused by similar issues.

We already created a [release plan](https://projects.eclipse.org/projects/ee4j.krazo/releases/1.1.0) for the upcoming 1.1.0 release and fully supporting CXF is one of the major goals. I hope to find a bit more time to work on this in the next days/weeks.

Thanks for your patience.

**Comment by jefrog1844** [comment] 2020-01-30 23:30
No problem.  Thanks for the feedback.

Jeff

**Comment by mthmulders** [comment] 2020-02-20 21:11
I've spoken with some IBM people at DevNexus. They suggested to disable the `X-Powered-By` (using [`<webContainer>`](https://openliberty.io/docs/ref/config/#webContainer.html) but that didn't make a difference.

I've posted the issue to their issue tracker as well: [OpenLiberty/open-liberty #10988](https://github.com/OpenLiberty/open-liberty/issues/10988).

**Comment by chkal** [comment] 2020-02-21 16:30
@mthmulders Thanks a lot! 

Unfortunately I don't find much time to work on the CXF compatibility at the moment. But improving support for CXF is definitely on our TODO list for Krazo 1.1.0. Maybe the upstream issue help to find the root cause of this.

**Comment by chkal** [comment] 2020-03-04 06:27
This issue has been fixed in OpenLiberty. See OpenLiberty/open-liberty#10988 for details.

@mthmulders Thanks a lot for reporting and for helping us to fix this issue! :beers:

**Closed by chkal** 2020-03-04 06:27 UTC
