### ISSUE TITLE
Krazo starting twice

### ISSUE THREAD

**Issue by mthmulders** [eclipse-ee4j/krazo#80] opened 2019-06-26 18:55 UTC
The [Install Guide for Servlet Containers](https://www.mvc-spec.org/krazo/docs/install-servlet.html) provides a sample web.xml file:

```xml


<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://java.sun.com/xml/ns/javaee"
         xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_4_0.xsd"
         version="4.0">

  <!-- omitted for brevity -->

</web-app>
```

When I do this, I notice that my application logs the following message **twice**:

    org.eclipse.krazo.bootstrap.Initializer.initialize Initializing Eclipse Krazo...

I wonder if this intentional. If not, adding the following to the root `web-app` fixed it for me:

```xml
metadata-complete="true"
```

I'm more than willing to provide a PR for this, but I'm not sure if it's correct. Also, I don't know where to find the website source ;-).

**Comment by chkal** [comment] 2019-06-27 04:53
Hi @mthmulders,

thanks for reporting this. Seeing this message twice is definitely weird. Actually there is code in Krazo that should prevent double initialization:

https://github.com/eclipse-ee4j/krazo/blob/d944a8cb1bf412da8a38e603cc95bf165ccb8b18/core/src/main/java/org/eclipse/krazo/bootstrap/Initializer.java#L57-L59

However, Krazo is bootstrapped once **per JAX-RS application**. So maybe your JAX-RS implementation is registered twice? Adding `metadata-complete=true` is a workaround, but I guess the root cause is something else. Could you share more details about your sample project. Perhaps post the contents of `WEB-INF/lib`?

**Comment by mthmulders** [comment] 2019-06-27 18:06
## Additional info
What I forgot to mention in the report, I'm using Apache Tomcat/9.0.21.

## Observations 
Without `metadata-complete="true"`, I'm seeing
1. First instance is started from `org.jboss.resteasy.plugins.server.servlet.Filter30Dispatcher` (which has the `@WebFilter` annotation).
1. Second instance is started from `org.jboss.resteasy.plugins.server.servlet.HttpServlet30Dispatcher` (which has the `@WebServlet` annotation).

If I add `metadata-complete="true"`, only the HttpServlet30Dispatcher-initiated app is started.

It's actually pretty strange, when I think of it, because `metadata-complete` is supposed to say that the container doesn't have to do classpath scanning, since `web.xml` is _complete_.

## WEB-INF/lib contents
To answer your question, my WEB-INF/lib looks like this:

```
mvc-servlet-container-0.1-SNAPSHOT $ ls -l WEB-INF/lib/
total 17712
-rw-r--r--  1 maarten  staff    69409 Apr  4 19:29 activation-1.1.1.jar
-rw-r--r--  1 maarten  staff   107519 Jun  7 19:39 cdi-api-2.0.SP1.jar
-rw-r--r--  1 maarten  staff    65100 Apr  4 19:29 classmate-1.3.4.jar
-rw-r--r--  1 maarten  staff   284184 Apr  4 19:29 commons-codec-1.10.jar
-rw-r--r--  1 maarten  staff   208700 Mar 27 06:54 commons-io-2.5.jar
-rw-r--r--  1 maarten  staff    61829 Mar 27 07:18 commons-logging-1.2.jar
-rw-r--r--  1 maarten  staff   704465 May 29 14:21 hibernate-validator-5.2.4.Final.jar
-rw-r--r--  1 maarten  staff   781831 Jun  8 09:37 httpclient-4.5.4.jar
-rw-r--r--  1 maarten  staff   325123 Jun 14 14:49 httpcore-4.4.7.jar
-rw-r--r--  1 maarten  staff  1535146 Jun 16 20:12 javaee-web-api-8.0.jar
-rw-r--r--  1 maarten  staff     2497 Mar 27 07:18 javax.inject-1.jar
-rw-r--r--  1 maarten  staff    23665 Jun 10 19:34 javax.json.bind-api-1.0.jar
-rw-r--r--  1 maarten  staff    17263 May  5 14:19 javax.mvc-api-1.0-pfd.jar
-rw-r--r--  1 maarten  staff    19197 Jun 16 20:12 jboss-annotations-api_1.2_spec-1.0.0.Final.jar
-rw-r--r--  1 maarten  staff    19943 Jun 16 20:12 jboss-annotations-api_1.3_spec-1.0.0.Final.jar
-rw-r--r--  1 maarten  staff   119024 Jun 16 20:12 jboss-classfilewriter-1.2.3.Final.jar
-rw-r--r--  1 maarten  staff    85726 Jun 16 20:12 jboss-el-api_3.0_spec-1.0.7.Final.jar
-rw-r--r--  1 maarten  staff    16245 Jun 16 20:12 jboss-interceptors-api_1.2_spec-1.0.0.Final.jar
-rw-r--r--  1 maarten  staff   131470 Jun 16 20:12 jboss-jaxb-api_2.3_spec-1.0.0.Final.jar
-rw-r--r--  1 maarten  staff   137644 Jun 16 20:12 jboss-jaxrs-api_2.1_spec-1.0.1.Final.jar
-rw-r--r--  1 maarten  staff    66711 May 29 14:21 jboss-logging-3.2.1.Final.jar
-rw-r--r--  1 maarten  staff     2254 Apr  8 14:20 jcip-annotations-1.0.jar
-rw-r--r--  1 maarten  staff   153232 Jun 26 19:24 krazo-core-1.0.0-SNAPSHOT.jar
-rw-r--r--  1 maarten  staff     8885 Jun 26 19:12 krazo-resteasy-1.0.0-SNAPSHOT.jar
-rw-r--r--  1 maarten  staff     2097 Apr  4 19:29 reactive-streams-1.0.2.jar
-rw-r--r--  1 maarten  staff    29647 Jun 16 20:12 resteasy-cdi-3.6.1.Final.jar
-rw-r--r--  1 maarten  staff  1039195 Jun 16 20:12 resteasy-jaxrs-3.6.1.Final.jar
-rw-r--r--  1 maarten  staff     8993 Jun 16 20:12 resteasy-servlet-initializer-3.6.1.Final.jar
-rw-r--r--  1 maarten  staff    25349 Jun 16 20:12 resteasy-validator-provider-11-3.6.1.Final.jar
-rw-r--r--  1 maarten  staff    63777 Apr  8 14:20 validation-api-1.1.0.Final.jar
-rw-r--r--  1 maarten  staff    32056 Jun 16 20:12 weld-api-3.0.SP4.jar
-rw-r--r--  1 maarten  staff  1659971 Jun 16 20:12 weld-core-impl-3.0.5.Final.jar
-rw-r--r--  1 maarten  staff    85612 Jun 16 20:12 weld-environment-common-3.0.5.Final.jar
-rw-r--r--  1 maarten  staff    17890 Jun 16 20:12 weld-jsf-3.0.5.Final.jar
-rw-r--r--  1 maarten  staff   819889 Jun 16 20:12 weld-probe-core-3.0.5.Final.jar
-rw-r--r--  1 maarten  staff    93862 Jun 16 20:12 weld-servlet-core-3.0.5.Final.jar
-rw-r--r--  1 maarten  staff    90917 Jun 16 20:12 weld-spi-3.0.SP4.jar
-rw-r--r--  1 maarten  staff    80014 Jun 16 20:12 weld-web-3.0.5.Final.jar
```

## Interpretation
I can see there's two versions of `org.jboss.spec.javax.annotation:jboss-annotations-api*`:
* jboss-annotations-api_1.2_spec-1.0.0.Final.jar
* jboss-annotations-api_1.3_spec-1.0.0.Final.jar

Looking at `mvn dependency:tree` output, both are pulled in via Weld:

```
+- org.jboss.weld.servlet:weld-servlet-core:jar:3.0.5.Final:compile
|  +- org.jboss.weld.environment:weld-environment-common:jar:3.0.5.Final:compile
|  |  \- org.jboss.weld:weld-core-impl:jar:3.0.5.Final:compile
|  |     +- org.jboss.spec.javax.annotation:jboss-annotations-api_1.3_spec:jar:1.0.0.Final:compile
```

and

```
+- org.jboss.resteasy:resteasy-cdi:jar:3.6.1.Final:compile
|  +- javax.validation:validation-api:jar:1.1.0.Final:compile
|  \- org.jboss.resteasy:resteasy-jaxrs:jar:3.6.1.Final:compile
|     +- org.jboss.spec.javax.annotation:jboss-annotations-api_1.2_spec:jar:1.0.0.Final:compile
```

Thanks to the artifact name being versioned, Maven cannot see that it's two version of the same artifact (at least, that's what I suspect). But the `@WebFilter` and `@WebServlet`  annotated classes aren't in that archive - they're in `org.jboss.resteasy:resteasy-jaxrs:jar:3.6.1.Final`. Now I'm a bit puzzled...

**Comment by chkal** [comment] 2019-06-29 09:34
@mthmulders Thanks for providing more details. A few comments:

> It's actually pretty strange, when I think of it, because `metadata-complete` is supposed to say that the container doesn't have to do classpath scanning, since `web.xml` is _complete_.

That's true. However, most frameworks use a `ServletContainerInitializer` today to ensure that filters/servlets are registered even if `metadata-complete` is set. In case of RESTEasy, it looks like only `HttpServlet30Dispatcher` is registered via the initializer:

https://github.com/resteasy/Resteasy/blob/ccb565ea87972cf032bea0bd66b96b380597e15c/resteasy-servlet-initializer/src/main/java/org/jboss/resteasy/plugins/servlet/ResteasyServletInitializer.java#L107-L110

The interesting thing is that the Krazo initialization is triggered via an JAX-RS feature. And actually it should be initialized only once (see `isAlreadyInitialized()` method mentioned above). So my guess is that:

  * Either `isAlreadyInitialized()` isn't working as expected
  * Or RESTEasy is actually initialized twice and therefore also initialized Krazo twice

Maybe debugging `isAlreadyInitialized()` can help?

**Comment by mthmulders** [comment] 2019-07-03 20:06
I've done some debugging in the aforementioned `isAlreadyInitialized()` method. There were two invocations:
1. Uses `configuration`: ResteasyProviderFactory @ 5054
1. Uses `configuration`: ResteasyProviderFactory @ 5214

So indeed RESTEasy seems to be instantiated twice. I've saved the two stacktraces and compared them:

```
$ diff -C 3 stack-1.txt stack-2.txt 
*** stack-1.txt	Sun Jun 30 12:09:50 2019
--- stack-2.txt	Sun Jun 30 12:09:58 2019
***************
*** 7,18 ****
  startInternal:261, ResteasyDeployment (org.jboss.resteasy.spi)
  start:88, ResteasyDeployment (org.jboss.resteasy.spi)
  init:119, ServletContainerDispatcher (org.jboss.resteasy.plugins.server.servlet)
! init:42, FilterDispatcher (org.jboss.resteasy.plugins.server.servlet)
! initFilter:270, ApplicationFilterConfig (org.apache.catalina.core)
! getFilter:251, ApplicationFilterConfig (org.apache.catalina.core)
! <init>:102, ApplicationFilterConfig (org.apache.catalina.core)
! filterStart:4530, StandardContext (org.apache.catalina.core)
! startInternal:5169, StandardContext (org.apache.catalina.core)
  start:183, LifecycleBase (org.apache.catalina.util)
  addChildInternal:717, ContainerBase (org.apache.catalina.core)
  addChild:690, ContainerBase (org.apache.catalina.core)
--- 7,18 ----
  startInternal:261, ResteasyDeployment (org.jboss.resteasy.spi)
  start:88, ResteasyDeployment (org.jboss.resteasy.spi)
  init:119, ServletContainerDispatcher (org.jboss.resteasy.plugins.server.servlet)
! init:36, HttpServletDispatcher (org.jboss.resteasy.plugins.server.servlet)
! initServlet:1122, StandardWrapper (org.apache.catalina.core)
! loadServlet:1077, StandardWrapper (org.apache.catalina.core)
! load:971, StandardWrapper (org.apache.catalina.core)
! loadOnStartup:4868, StandardContext (org.apache.catalina.core)
! startInternal:5177, StandardContext (org.apache.catalina.core)
  start:183, LifecycleBase (org.apache.catalina.util)
  addChildInternal:717, ContainerBase (org.apache.catalina.core)
  addChild:690, ContainerBase (org.apache.catalina.core)
```

**Comment by chkal** [comment] 2019-07-04 15:47
This really looks like RESTEasy is bootstrapping twice in this very simple example with `metadata-complete=false`. 

@asoldano Any idea? Do you think we should file an issue in the RESTEasy issue tracker about this?

**Comment by asoldano** [comment] 2019-07-05 13:28
@chkal yes please. I don't have time atm for investigating this, but someone from the team might.

**Comment by chkal** [comment] 2019-07-06 05:59
@asoldano Thanks a lot!

@mthmulders Could you file a corresponding issue in the RESTEasy issue tracker?

**Comment by mthmulders** [comment] 2019-07-07 13:18
For reference, the reproduction project is [here at GitHub](https://github.com/mthmulders/mvc-servlet-container).
The RESTEasy issue is [at JBoss JIRA](https://issues.jboss.org/browse/RESTEASY-2289).

**Comment by chkal** [comment] 2019-07-08 06:09
Awesome, thanks a lot!

**Comment by mthmulders** [comment] 2019-09-14 06:05
According to the [response in the RESTEasy issue tracker](https://issues.jboss.org/browse/RESTEASY-2289?focusedCommentId=13784274&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13784274), the behavior is expected. Adding `metadata-complete="true"` should be the way to address it.

**Comment by chkal** [comment] 2019-09-14 08:35
Hi @mthmulders. Thanks for the update. To be honest, I'm quite surprised by this response and just posted [another comment](https://issues.jboss.org/browse/RESTEASY-2289?focusedCommentId=13784320&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13784320) to the issue.

I know that setting `metadata-complete=true` works in this case, but this will also deactivate auto-discovery for ALL classes and libraries within the application.

**Comment by mthmulders** [comment] 2019-10-03 11:02
I've updated the [sample repo](https://github.com/mthmulders/mvc-servlet-container) to go without the RESTEasy Servlet Initializer module. What I'm seeing is that the KrazoServletContextListener is starting; it correctly detects the Controller classes and publishes them on the ServletContext.

From what I understand of how Krazo works, the `UriTemplateParser` should be initialised as it detects the exact paths that the application publishes. I have a breakpoint in its `init()` method but that doesn't get hit - not during app startup and also not when I access my app. Instead I'm greeted by a Tomcat-generated HTTP 404.

I'm using Apache Tomcat/9.0.26, by the way.

**Comment by chkal** [comment] 2019-10-03 12:44
@mthmulders I just had a look at your sample app. Many thanks for providing that.

I can reproduce the issue you are describing. But for me it looks like RESTEasy isn't started at all. 

I removed all MVC dependencies from the project and replace the controller with a simple JAX-RS resource. And for some reason this also doesn't work. I also tried to follow the steps described in chapter "Older servlet containers" of the RESTEasy manual (adding the dispatcher servlet manually via web.xml), but no luck.

For some reason the app only works using the `resteasy-servlet-initializer` module. Without it, I'm unable to get even a simple plain JAX-RS example to work correctly.

**Comment by mthmulders** [comment] 2019-10-03 13:18
Well, that's interesting. I'm seeing the same behavior when updating web.xml.

The only way to start RESTEasy in a modern Servlet container is to use the RESTEasy Servlet Initializer. As you have pointed out in [RESTEASY-2289](https://issues.jboss.org/browse/RESTEASY-2289) it will basically start _two_ JAX-RS applications in one webapp, which I personally think is not what you would want - regardless of whether you use Krazo on top of it or not.

**Comment by mthmulders** [comment] 2019-10-15 11:07
Is this covered enough by updating the docs (mvc-spec/www.mvc-spec.org/pull/50) or should we take additional action on this topic?

**Comment by chkal** [comment] 2019-10-15 11:23
I guess we can close this issue. I still think that this is caused by the RESTEasy code. Let's hope that the RESTEasy team finds a way to simplify the bootstrapping process.

**Closed by chkal** 2019-10-15 11:23 UTC

**Comment by mthmulders** [comment] 2019-10-15 11:34
I share your opinion. Unfortunately that also means we can't really do much more than we do right now...
