### ISSUE TITLE
@MvcBinding Annotation doesn't work for example from chapter 3.3 of MVC 1.0 spec

### ISSUE THREAD

**Issue by TrojaA** [eclipse-ee4j/krazo#173] opened 2020-04-04 18:31 UTC
I tried to implement the example from chapter 3.3 of the mvc 1.0 specs, but the MvcBinding annotation doesn't seem to work within a controller. Instead of invoking the ressource method a ViolationReport is sent to the client containing the validation error.
This seems to be controller related, since I ran successfully the BindingBase test from mvc-tck. (This test implements the validation constraint in the bean class)

Did I do something wrong? I'm not sure whether it's a fault on my side, but I can reproduce the problem on both WildFly 18 and Tomcat 9.

P.S.: I couldn't debug the problem further, because I'm not that familiar with this project so far.

**Comment by erdlet** [comment] 2020-04-05 15:08
Hi @TrojaA,

can you please post or link your code, so we can have a look into this? Thanks!

**Comment by chkal** [comment] 2020-04-11 10:56
@TrojaA Thanks for reporting this. More details about your setup would definitely be very helpful. Maybe you can even provide a reproducer app?

**Comment by erdlet** [comment] 2020-07-06 07:12
As there is no feedback to this since 3 months, I'll close this issue. In case there is new information available, we'll reopen it.

**Closed by erdlet** 2020-07-06 07:12 UTC
Labels: question
