### ISSUE TITLE
Some regex flags are not properly cleared for @UriRef

### ISSUE THREAD

**Issue by kalgon** [eclipse-ee4j/krazo#182] opened 2020-05-27 12:39 UTC
A resource method annotated with `@UriRef(...) @Path("foo/{bar:(?i)[a-z]{3}}")` (notice the `(?i`) in front of the regex to switch to case-insensitive mode) won't produce correct URIs with `MvcContext.uri()` (in my case, it gives `foo/%7Bbar:(?i)%5Ba-z%5D%063%07%7D`). If the case-insensitive flag is removed then it works fine.

**Comment by lefloh** [comment] 2020-06-07 15:21
Thanks for reporting and sorry for the delayed response.
I'm not able to reproduce it.
Could you please tell which JAX-RS implementation you are using?
Could you also please test what the result of following code is:

```
javax.ws.rs.core.UriBuilder.fromUri("foo/{bar:(?i)[a-z]{3}}").build("baz")
```

**Comment by kalgon** [comment] 2020-06-08 14:44
I tested your code with the last version of resteasy (4.5.3.Final) and it gave `foo/%7Bbar:(?i)%5Ba-z%5Dbaz%07`.

Is `UriBuilder.fromUri()` supposed to clear regexes in path parameters?

**Comment by chkal** [comment] 2020-06-09 11:11
> Is `UriBuilder.fromUri()` supposed to clear regexes in path parameters?

Good question. AFAIK the spec isn't clear about this. But maybe it would be a good idea to simply ignore the regex patterns?

**Comment by lefloh** [comment] 2020-06-09 19:26
Would be an easy fix. But then we could render URI's which won't be matched.
I'm not sure what the expectation is in that case.

**Comment by chkal** [comment] 2020-06-11 10:09
A small update. My comment may have been a bit confusing.

Actually Krazo uses the JAX-RS ` UriBuilder` internally. So if this builder doesn't handle `(?i)` correctly, this is most likely an issue with RESTEasy and nothing we can fix on our side.

@lefloh Correct me if I'm wrong. :-)

**Comment by chkal** [comment] 2020-06-11 10:15
BTW: [RESTEASY-2607](https://issues.redhat.com/browse/RESTEASY-2607) is the corresponding upstream issue.

**Comment by lefloh** [comment] 2020-06-11 10:22
Yes, we're using the JAX-RS `UriBuilder` and I couldn't reproduce the reported issue with Jersey.
I'll close that issue now.
@kalgon thanks for reporting and feel free to reopen it if it can't be fixed by RestEasy.

**Closed by lefloh** 2020-06-11 10:22 UTC
Labels: bug
